blank_issues_enabled: false
contact_links:
  - name: Ask PyroRatnaGram related questions
    url: https://stackoverflow.com/questions/tagged/PyroRatnaGram
    about: This place is only for reporting issues about PyroRatnaGram. You can ask questions at StackOverflow.
  - name: Join the Telegram Chat
    url: https://t.me/MayuriChan_Chat
    about: Join the official Chat and stay tuned for news, updates and announcements.